// form-ang/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, RouterLink],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'form-ang';
}



<div class="@container h-full min-h-full flex flex-col">
  <header class="p-4 shadow-sm shadow-blue-500/50">
     <h1><a routerLink="/">Forms</a></h1>
  </header>

  <div class="grow-1 basis-0 overflow-auto p-4">
    <router-outlet />
  </div>
</div>

// src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
import HelloWorld from './components/HelloWorld.vue'
</script>

<template>

  <div class="@container h-full min-h-full flex flex-col">
    
    <header class="p-4 shadow-sm shadow-blue-500/50">
      <h1><RouterLink to="/">Forms</RouterLink></h1>
    </header>

    <div class="grow-1 basis-0 overflow-auto p-4">
      <RouterView />
    </div>
  </div>


</template>

<style scoped>
</style>
